config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    //$routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/', ['controller' => 'Views', 'action' => 'index']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/ArticlesTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Articles Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Categories
 * @property \Cake\ORM\Association\HasMany $Comments
 *
 * @method \App\Model\Entity\Article get($primaryKey, $options = [])
 * @method \App\Model\Entity\Article newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Article[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Article|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Article patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Article[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Article findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */class ArticlesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('articles');
        $this->displayField('title');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id'
        ]);
        $this->hasMany('Comments', [
            'foreignKey' => 'article_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');
        $validator
            ->requirePresence('title', 'create')
            ->notEmpty('title');
        $validator
            ->requirePresence('body', 'create')
            ->notEmpty('body');
        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['category_id'], 'Categories'));

        return $rules;
    }
}

src/Model/Table/CommentsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Comments Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Articles
 * @property \Cake\ORM\Association\BelongsTo $Users
 * @property \Cake\ORM\Association\BelongsTo $ParentComments
 * @property \Cake\ORM\Association\HasMany $ChildComments
 *
 * @method \App\Model\Entity\Comment get($primaryKey, $options = [])
 * @method \App\Model\Entity\Comment newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Comment[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Comment|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Comment patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Comment[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Comment findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 * @mixin \Cake\ORM\Behavior\TreeBehavior
 */class CommentsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('comments');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');
        $this->addBehavior('Tree');

        $this->belongsTo('Articles', [
            'foreignKey' => 'article_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id'
        ]);
        $this->belongsTo('ParentComments', [
            'className' => 'Comments',
            'foreignKey' => 'parent_id'
        ]);
        $this->hasMany('ChildComments', [
            'className' => 'Comments',
            'foreignKey' => 'parent_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');
        $validator
            ->allowEmpty('title');
        $validator
            ->requirePresence('body', 'create')
            ->notEmpty('body');
        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        $rules->add($rules->existsIn(['parent_id'], 'ParentComments'));

        return $rules;
    }
}

src/Template/Admin/article_add.ctp
<!-- File: src/Template/Admin/article_add.ctp -->

<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');
?>
<h3>Add Article</h3>
<?php
    echo $this->Form->create($article);
    //just added the categories input
    echo $this->Form->input('category_id');
    echo $this->Form->input('title');
    echo $this->Form->input('body', ['rows' => '10']);
    echo $this->Form->button(__('save Article'));
    echo $this->Form->end();

    $this->end();
?>

src/Template/Admin/article_edit.ctp
<!-- File: src/Template/Admin/article_edit.ctp -->

<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');
?>
<h3>Edit Article</h3>
<?php
    echo $this->Form->create($article);
    echo $this->Form->input('title');
    echo $this->Form->input('category_id');
    echo $this->Form->input('body', ['rows' => '10']);
    echo $this->Form->button(__('Save Article'));
    echo $this->Form->end();

    $this->end();
?>

src/Template/Admin/categories_list.ctp
<!-- File://src/Template/Admin/categories_list.ctp -->

<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');
?>
    <h3><?= __('Categories List') ?></h3>
    <p><?= $this->Html->link('New Categories', ['action' => 'categoryAdd']) ?></p>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Created</th>
                <th>Articles count</th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($categories as $category): ?>
            <tr>
                <td><?= h($category->name) ?></td>
                <td><?= h($category->description) ?></td>
                <td><?= h($category->created->format(DATE_RFC850)) ?></td>
                <td><?= $this->cell("Counter::display_category", [$category->id]) ?>件</td>
                <td class="actions">
                    <div class="btn-group-vertical">
                        <?= $this->Html->link($this->Html->tag('span', 'Edit'), ['action' => 'categoryEdit', $category->id],['class' => 'btn btn-default', 'escape' => false]) ?>
                        <?= $this->Form->postLink($this->Html->tag('span', 'Delete'), ['action' => 'categoryDelete', $category->id],
                                ['confirm' => __('Are you sure you want to delete # {0}?', $category->id), 'class' => 'btn btn-default', 'escape' => false]) ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    
    <nav aria-label="ページ送り">
        <ul class="pagination">
            <?= $this->Paginator->numbers(
                ['before' => $this->Paginator->prev('<<'),
                 'after' => $this->Paginator->next('>>')]
            ); ?>
        </ul>
    </nav>
<?php $this->end(); ?>

src/Template/Admin/category_add.ctp
<!-- File:src/Template/Admin/category_add.ctp -->

<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');
?>
<h3>Add Category</h3>
<?= $this->Form->create($category) ?>
<fieldset>
    <?php
        echo $this->Form->input('parent_id', [
            'options' => $parentCategories,
            'empty' => 'No parent category'
        ]);
        echo $this->Form->input('name');
        echo $this->Form->input('description');
    ?>
</fieldset>
<?= $this->Form->button(__('Submit')) ?>
<?= $this->Form->end(); ?>

<?php $this->end() ?>

src/Template/Admin/category_edit.ctp
<!-- File: src/Template/Admin/category_edit.ctp -->

<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');
?>
<?= $this->Form->create($category) ?>
    <fieldset>
        <legend><?= __('Edit Category') ?></legend>
        <?php
            echo $this->Form->input('parent_id', [
                'options' => $parentCategories,
                'empty' => 'No parent category'
            ]);
            echo $this->Form->input('name');
            echo $this->Form->input('description');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
<?= $this->Form->end() ?>

<?php $this->end(); ?>

src/Template/Admin/comment_add.ctp
<!-- File: src/Template/Admin/comment_add.ctp -->

<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');

    $this->Form->create($comment,
        ['url' =>['action' => 'commentAdd']]);
        echo $this->element('Form/reply_form',[
                "commentId" => $commentId,
                "articleId" => $articleId
        ]);
    $this->Form->end();

    $this->end();
?>

src/Template/Admin/comments_list.ctp
<!-- File: src/Template/Admin/comments_list.ctp -->

<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');
?>
    <h3><?= __('Comments List') ?></h3>
    <?php foreach($comments as $comment): ?>
        <div class="panel panel-default comment_panel">
            <div class="panel-body">
                <p><strong><?= h($comment->title) ?></strong></p>
                <p><?= nl2br(h($comment->body)) ?></p>
                <p class="text-right"><small>Created: <?= $comment->created->format(DATE_RFC850) ?></small></p>
                <p class="text-right"><small>Article: <?= $comment->article->title ?></small></p>
                <!-- 返信件数 -->
                <p class="text-right"><a data-toggle="collapse" data-target="#rc<?= $comment->id ?>">▼返信件数:
                    <?= $this->cell("Counter::display_reply", [$comment->id])->render(); ?></a>
                </p>
                <!-- 返信コメント -->
                <?php if(!empty($comment->child_comments)): ?>
                    <div id="rc<?= $comment->id ?>" class="collapse">
                        <?php foreach($comment->child_comments as $childComments): ?>
                            <div class="panel panel-default replyComments">
                                <div class="panel-body">
                                    <p><strong><?= h($childComments->title) ?></strong></p>
                                    <p><?= nl2br(h($childComments->body)) ?></p>
                                    <p class="text-right">
                                        <small>Created: <?= $childComments->created->format(DATE_RFC850) ?></small>
                                    </p>
                                    <?= $this->Form->postLink($this->Html->tag('span', 'Delete'), ['action' => 'commentDelete', $comment->id],
                                        ['confirm' => __('Are you sure you want to delete # {0}?', $comment->id),
                                         'class' => 'btn btn-default pull-right', 'escape' => false])
                                    ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <?= $this->Form->postLink($this->Html->tag('span', '削除'), ['action' => 'commentDelete', $comment->id],
                    ['confirm' => __('Are you sure you want to delete # {0}?', $comment->id),
                    'class' => 'btn btn-default pull-right', 'escape' => false])
                ?>
                <button type="button" class="btn btn-default pull-right" data-toggle="collapse" data-target="#<?= $comment->id ?>">
                    <?= __('返信') ?>
                </button>
                <!-- 返信用フォーム -->
                <div id="<?= $comment->id ?>" class="collapse reply">
                    <?= $this->Form->create($comment,
                        ['url' =>['action' => 'commentAdd']])
                    ?>
                        <?= $this->element('Form/reply_form',[
                            "commentId" => $comment->id,
                            "articleId" => $comment->article->id
                        ]) ?>
                    <?= $this->Form->end() ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    
    <nav aria-label="ページ送り">
        <ul class="pagination">
            <?= $this->Paginator->numbers(
                ['before' => $this->Paginator->prev('<<'),
                 'after' => $this->Paginator->next('>>')]
            ); ?>
        </ul>
    </nav>
<?php $this->end(); ?>

src/Template/Admin/index.ctp
<!-- File://src/Template/Admin/index.ctp -->
<?php
    $this->extend('/Common/admin_template');
    $this->start('main_content');
?>
    <h3><?= __('Articles List') ?></h3>
    
    <p><?= $this->Html->link('New Articles', ['action' => 'articleAdd']) ?></p>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Category Name</th>
                <th>Created</th>
                <th>Modified</th>
                <th>Reply count</th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($articles as $article): ?>
            <tr>
                <td><?= h($article->title) ?></td>
                <td>
                    <?php if(!empty($article->category->name)):?>
                        <?= h($article->category->name) ?>
                    <?php endif; ?>
                </td>
                <td><?= h($article->created->format(DATE_RFC850)) ?></td>
                <td><?= h($article->modified->format(DATE_RFC850)) ?></td>
                <td><?= $this->cell("Counter::display_comment", [$article->id]) ?></td>
                <td class="actions">
                    <div class="btn-group-vertical">
                        <?= $this->Html->link($this->Html->tag('span', 'Edit'), ['action' => 'articleEdit', $article->id],['class' => 'btn btn-default', 'escape' => false]) ?>
                        <?= $this->Form->postLink($this->Html->tag('span', 'Delete'), ['action' => 'articleDelete', $article->id],
                                ['confirm' => __('Are you sure you want to delete # {0}?', $article->id), 'class' => 'btn btn-default', 'escape' => false]) ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    
    <nav aria-label="ページ送り">
        <ul class="pagination">
            <?= $this->Paginator->numbers(
                ['before' => $this->Paginator->prev('<<'),
                 'after' => $this->Paginator->next('>>')]
            ); ?>
        </ul>
    </nav>
<?php $this->end(); ?>